template_path: templates/database.yaml

parameters:
  DBName: urlshortener
  DBAllocatedStorage: "20"
  DBInstanceClass: "db.t2.micro"
  DBUser: test
  DBPassword: DatabasePasswordProd
  VPC: {{ var.vpc}}
  Subnet0: {{ var.subnet0 }}
  Subnet1: {{ var.subnet1 }}
  Subnet2: {{ var.subnet2 }}
  InstanceSecurityGroup: !stack_output webservers::WebServerSecurityGroup
